hashapp/urls.py
from django.contrib import admin
from django.urls import path, include
from sha256 import views as ShaViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', ShaViews.UserLoginView.as_view(), name='login'),
    path('register/', ShaViews.RegisterView.as_view(), name='register'),
    path('logout/', ShaViews.LogoutView.as_view(), name='logout'),
    path('account/', ShaViews.AccountView.as_view(), name='account'),
    path('delete-account/<int:pk>/', ShaViews.DeleteAccountView.as_view(), name='delete-account'),
    path('pass-change/', ShaViews.PasswordChange.as_view(), name='pass-change'),
    path('', include('sha256.urls')),
]

sha256/urls.py
from django.urls import path

from . import views


app_name = 'sha256'


urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('hash-gen/', views.HashGenerator.as_view(), name='hash-gen'),
    path('hash-list/', views.HashListView.as_view(), name='hash-list'),
    path('save-text-hash/', views.SaveHash.as_view(), name='save-text-hash')
]

sha256/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Hash(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    hash = models.CharField(max_length=64)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

sha256/forms.py
from django import forms
from .models import Hash


class HashForm(forms.ModelForm):

    class Meta:
        model = Hash
        fields = 'text',
        widgets = {
            'text': forms.Textarea
        }

    def save(self, commit=True, user=None, hash=None):
        text = self.cleaned_data.get('text')
        instance = Hash(user=user, text=text, hash=hash)
        instance.save()
        return instance

sha256/views.py
import hashlib
from django.contrib.auth import authenticate, get_user_model, login, logout, update_session_auth_hash
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView as LogOutView, PasswordChangeView
from django.db.models import Q
from django.http import JsonResponse, HttpResponseRedirect
# from django.contrib.auth.urls import
from django.urls import reverse_lazy, reverse
from django.template.loader import render_to_string
from django.views.generic import FormView, View, ListView, CreateView
from django.views.generic import TemplateView, DeleteView

from .models import Hash
from .forms import HashForm

User = get_user_model()


def hash_generator(text):
    return hashlib.sha256(text.encode('utf-8')).hexdigest()


class IndexView(FormView):
    template_name = 'sha256/index.html'
    form_class = HashForm


class HashGenerator(View):
    def post(self, request, *args, **kwargs):
        """generating hashing from text"""
        form = HashForm(request.POST or None)
        if form.is_valid():
            text = form.cleaned_data.get('text')
            hash = hash_generator(text)
            return JsonResponse({'hash': hash})
        return JsonResponse({'msg': 'invalid text'}, status=400)


class UserLoginView(LoginView):
    form_class = AuthenticationForm
    success_url = reverse_lazy('account')

    def form_valid(self, form):
        user = authenticate(request=self.request, **form.cleaned_data)
        if user:
            login(self.request, user)
            if self.request.is_ajax():
                return JsonResponse({'msg': 'authentication successful'})
            return HttpResponseRedirect(self.get_success_url())
        form.add_error(None, 'Wrong username/password please try again')
        return self.form_invalid(form)

    def get_success_url(self):
        url = self.get_redirect_url()
        return url if url else self.success_url

    def render_to_response(self, context, **response_kwargs):
        if context['form'].errors:
            status = 400
        else:
            status = 200
        if self.request.is_ajax():
            rendered_form = render_to_string('sha256/form.html', context, request=self.request)
            return JsonResponse({'form': rendered_form}, status=status)
        return super().render_to_response(context, **response_kwargs)


class RegisterView(FormView):
    form_class = UserCreationForm
    template_name = 'registration/login.html'

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password1')
        User.objects.create_user(
            username=username,
            password=password
        )
        user = authenticate(self.request, username=username, password=password)
        login(self.request, user)
        if self.request.is_ajax():
            return JsonResponse({'msg': 'user created'})
        return HttpResponseRedirect(reverse('account'))

    def render_to_response(self, context, **response_kwargs):
        if self.request.is_ajax():
            rendered_form = render_to_string('sha256/form.html', context, request=self.request)
            return JsonResponse({'form': rendered_form},
                                status=400 if context['form'].errors else 200)
        return super().render_to_response(context, **response_kwargs)


class LogoutView(LogOutView):
    def render_to_response(self, context, **response_kwargs):
        if self.request.is_ajax():
            return JsonResponse({'msg': 'logged out'})
        return HttpResponseRedirect(reverse('index'))


class AccountView(LoginRequiredMixin, TemplateView):
    template_name = 'sha256/account.html'


class DeleteAccountView(LoginRequiredMixin, DeleteView):
    model = User
    success_url = '/'

    def delete(self, request, *args, **kwargs):
        logout(request)
        return super().delete(request, *args, **kwargs)

    def render_to_response(self, context, **response_kwargs):
        if self.request.is_ajax():
            render_modal_body = render_to_string('sha256/delete_account.html', context={'user': self.request.user},
                                                 request=self.request)
            return JsonResponse({'modal-body': render_modal_body})


class PasswordChange(PasswordChangeView):

    def render_to_response(self, context, **response_kwargs):
        if context['form'].errors:
            status = 400
        else:
            status = 200
        render_form = render_to_string('sha256/form.html', context=context, request=self.request)
        return JsonResponse({'form': render_form}, status=status)

    def form_valid(self, form):
        form.save()
        update_session_auth_hash(self.request, form.user)
        return JsonResponse({'msg': 'password successfully changed'})


class HashListView(LoginRequiredMixin, ListView):
    def render_to_response(self, context, **response_kwargs):
        render_list = render_to_string('sha256/saved_hashes.html', context=context)
        return JsonResponse({'list': render_list})

    def get_queryset(self):
        queryset = Hash.objects.filter(user=self.request.user)
        query = self.request.GET.get('q')
        if query:
            queryset = queryset.filter(Q(text=query) | Q(hash=query))
        return queryset


class SaveHash(LoginRequiredMixin, CreateView):
    form_class = HashForm
    model = Hash

    def form_valid(self, form):
        text = form.cleaned_data.get('text')
        hash = form.save(user=self.request.user, hash=hash_generator(text))
        return JsonResponse({hash.text: hash.hash}, status=201)

    def render_to_response(self, context, **response_kwargs):
        render_form = render_to_string('sha256/form.html', context=context, request=self.request)
        return JsonResponse({'form': render_form})

sha256/templates/sha256/account.html
<!DOCTYPE html>
<!--{% load static %}-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">-->
    <link rel="stylesheet" href="../../../static/css/bootstrap.css">
    <title>Title</title>
</head>
<body class="bg-dark overflow-hidden">

<div class="account-page">
    <div class="d-flex flex-column flex-sm-row align-items-center justify-content-center" style="height: 100vh;">
        <button class="text-hash btn btn-success mx-1 my-3">Display saved Text/Hash</button>
        <button class="pass-change btn btn-primary mx-1 my-3">Change password</button>
        <a class="logout btn btn-warning mx-1 my-3" href="{% url 'logout' %}">logout</a>
        <button class="btn btn-danger mx-1 my-3">Delete Account</button>
    </div>
</div>

<div class="modal-sec">
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary d-none modal-btn" data-toggle="modal" data-target="#exampleModal">
        Launch demo modal
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-lg">
            <div class="modal-content">
                <div class="modal-body">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h5 class="text-center">Register</h5>
                    <div class="modal-body-inner"></div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="../../../static/js/jquery.js"></script>
<!--<script src="../../../static/js/popper.js"></script>-->
<script src="../../../static/js/bootstrap.js"></script>
<script src="../../../static/js/CustomJs.js"></script>
<!--<script src="{% static 'js/jquery.js' %}"></script>-->
<!--<script src="{% static 'js/popper.js' %}"></script>-->
<!--<script src="{% static 'js/bootstrap.js' %}"></script>-->
</body>
</html>

sha256/templates/sha256/delete_account.html
<div class="d-flex flex-column">
    <h3>Are you sure to delete this account?</h3>
    <div class="">
        <form method="POST">
            {% csrf_token %}
            <input type="hidden" value="{{ user.id }}">
            <input type="submit" value="Yes" class="btn btn-outline-danger">
        </form>
        <button class="btn btn-success">Cancel</button>
    </div>
</div>

sha256/templates/sha256/form.html
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" class="btn btn-success">
</form>

sha256/templates/sha256/index.html
{% block content %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        <h2>please enter your text here</h2>
        {{ form.as_p }}
        <input type="submit" value="Submit" class="btn btn-warning">
    </form>
</div>
{% endblock %}

sha256/templates/sha256/saved_hashes.html
<div class="">
    <div class="search">
        <form method="POST">
            {% csrf_token %}
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Add words here">
                <input type="submit" value="Search" class="btn btn-warning">
            </div>
        </form>
    </div>

    <table class="table table-striped">
        {% if hash_list %}
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Text</th>
            <th scope="col">Hash</th>
            <th scope="col">created date</th>
        </tr>
        </thead>
        <tbody>
        {% for item in hash_list %}
        <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{item.text}}</td>
            <td>{{item.hash}}</td>
            <td>{{item.created_date}}</td>
        </tr>
        {% endfor %}
        </tbody>
        {% else %}
        <h3>No data <strong>Found</strong></h3>
        {% endif %}
    </table>
</div>

templates/base.html
<!DOCTYPE html>
<!--{% load static %}-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">-->
    <link rel="stylesheet" href="../static/css/bootstrap.css">
    <title>Title</title>
</head>
<body class="bg-dark overflow-hidden">

<div class="d-flex align-items-center justify-content-center" style="height: 100vh;">
    <div class="row my-5">
        <div class="col-10 col-sm-12 mx-auto">
            <div class="bg-light rounded d-flex flex-column">
                <div class="authentication my-1 align-self-end mr-2 mb-5 text-primary pointer-event">
                    <a href="" class="register">Register</a>/
                    <a href="" class="login">Login</a>
                    <a href="{% url 'sha256:account' %}" class="account d-none">My Account</a>
                    <a href="{% url 'logout' %}" class="logout d-none">Log out</a>
                </div>
                <h1 class="text-center">SHA256 Generator</h1>
                <div class="hashForm px-5 pt-3">
                    <form>
                        <label for="text">Text</label>
                        <textarea name="text" id="text" cols="60" rows="10" class="form-control"></textarea>
                    </form>
                </div>
                <div class="buttons my-3 d-flex justify-content-center">
                    <button class="btn btn-warning mr-3 generate">Generate Hash</button>
                    <button class="btn btn-primary clear">Clear</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal-sec">
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary d-none modal-btn" data-toggle="modal" data-target="#exampleModal">
      Launch demo modal
    </button>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
          <div class="modal-body">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <h5 class="text-center">Register</h5>
              <div class="modal-body-inner"></div>
          </div>
        </div>
      </div>
    </div>
</div>

<script src="../static/js/jquery.js"></script>
<script src="../static/js/popper.js"></script>
<script src="../static/js/bootstrap.js"></script>
<script src="../static/js/CustomJs.js"></script>
<!--<script src="{% static 'js/jquery.js' %}"></script>-->
<!--<script src="{% static 'js/popper.js' %}"></script>-->
<!--<script src="{% static 'js/bootstrap.js' %}"></script>-->
</body>
</html>